apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: arket
  labels:
    app: arket
    service: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: api-service
      app: arket
  template:
    metadata:
      labels:
         app: arket
         service: api-service
    
    spec: 
      containers:
          - name: api-service
          
            image: abdulwahabmsalih/arket-api:dcf4419a2835ad231eec48ff09f31e35aec06bdf
            imagePullPolicy: Always
            ports:
              - containerPort: 3001
                name: http
            env:
              - name: NODE_ENV
                valueFrom:
                  configMapKeyRef:
                    name: arket-config
                    key: NODE_ENV
              - name: PORT
                valueFrom:
                  configMapKeyRef:
                    name: arket-config
                    key: API_PORT
              - name: WORKER_URL
                valueFrom:
                  configMapKeyRef:
                    name: arket-config
                    key: WORKER_URL
              - name: ALLOWED_ORIGINS
                valueFrom:
                  configMapKeyRef:
                    name: arket-config
                    key: ALLOWED_ORIGINS
              - name: SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: arket-secrets
                    key: API_SECRET_KEY



---

apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: arket
  labels:
    app: arket
    service: api-service
spec:
  type: ClusterIP
  selector:
    service: api-service
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP