apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: arket
  labels:
    app: arket
    service: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arket
      service: frontend
  template:
    metadata:
      labels:
        app: arket
        service: frontend
    spec:
      containers:
      - name: frontend
        image: abdulwahabmsalih/arket-frontend:c065f4715fb2718dd9eb82d5ed3d9d78bd13a486
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: arket
  labels:
    app: arket
    service: frontend
spec:
  selector:
    service: frontend
    
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  
    
